services:
  backend:
    container_name: samLibrary-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
    networks:
      - samLibrary-network

  frontend:
    container_name: samLibrary-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_PROD_BACKEND_URL=${REACT_APP_PROD_BACKEND_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - samLibrary-network

networks:
  samLibrary-network:
    driver: bridge
