services:
  backend:
    container_name: samLibrary-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
          - ./config/bucketKey.json:/config/bucketKey.json
    restart: always

  frontend:
    container_name: samLibrary-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_PROD_BACKEND_API_URL=${REACT_APP_PROD_BACKEND_API_URL}
      - REACT_APP_PROD_BACKEND_URL=${REACT_APP_PROD_BACKEND_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always